### ISSUE TITLE
Encoded html not being converted to markdown properly

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/file2txt#11]
```
python3 file2txt.py \
  --mode html \
  --file tests/files/html/fanged_data_decoded.html \
  --output examples/test2 \
  --defang false \
  --extract_text_from_image false
```

When entering encoded html, the script simply turns it into encoded html.

It should do the next steps and convert to markdown (stripping html tags).

Essentially it is missing the final part; to go through the same pipeline as when decoded html is entered,

https://github.com/muchdogesec/file2txt?tab=readme-ov-file#a-note-on-html-encoding-for-html-and-html_article-modes

**Comment by fqrious** [comment]
but why you would ever have encoded html?

`.html` file is never encoded or wrapped in `CDATA`, if it is then it's no longer a `text/html`

**Comment by himynamesdave** [comment]
@fqrious what I'm trying to account for here is inputs for Obstracts which gets data in these 3 formats.

The question being; does Obstracts handle conversion of encoded / Cdata data properly?

**Comment by fqrious** [comment]
Yes, obstracts does. Because webpages (html) on the Internet are never encoded or wrapped in CDATA

**Comment by himynamesdave** [comment]
Yea, I wasn't really thinking it through! Thanks for clarifying!
