### ISSUE TITLE
Add md mode

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/file2txt#16]
txt mode  (added for stixify) is good for text files, but it does not extract images out of file (which is expected).

What i realised is people may also put in markdown (from which we should extract images, and text from images).

Thus we need to add a markdown mode, as described here

https://github.com/muchdogesec/file2txt/commit/94403624190af084eee84a5cb244b0dd0d0965b9

**Comment by fqrious** [comment]
Extracting images from markdown is hard, regular expression would extract non-images as images. For example, if an image is in code block, it's not supposed to be extracted but that's not something I can achieve with regular expression
